name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label:
      - 'feature'
      - 'enhance'
      - 'experimental'
      - 'documentation'
  - title: 'ğŸ› Bugfix'
    labels: 'bug fix'
  - title: 'ğŸª¡ Refactoring'
    label: 'refactor'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  $CHANGES
  ## Changes
  <!-- Changes must be included here! -->
